name: deploy
on:  
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
          
    - name: Set up Node.js version 18
      uses: actions/setup-node@v4
      with:
        node-version: 18
        cache: 'npm'
            
    - name: npm install npm
      run: |     
        npm ci
        npm build
        npm m3u
            
    - name: "Jekyll theme"
      run: mv ./_config.temp.yml ./m3u/_config.yml 
      
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./m3u
        enable_jekyll: true
        cname: m3u.vodtv.cn
