name: deploy
on:  
  watch:
    types: [started]
  schedule:
    - cron: '30 5,17 * * *'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v4
        - name: Setup Node.js
          uses: actions/setup-node@v1
          with:
            cache: "pnpm"
            
        - name: npm install pnpm
          run: |     
            npm install pnpm -g
            pnpm i
            pnpm run build
            pnpm run deploy
            
        - name: "Jekyll theme"
          run: mv ./_config.temp.yml ./m3u/_config.yml 
        - name: Deploy to GitHub Pages
          uses: peaceiris/actions-gh-pages@v3
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_dir: ./m3u
            enable_jekyll: true
            cname: m3u.vodtv.cn
