name: update
on:  
  watch:
    types: [started]
  schedule:
   - cron:  '0 0,8 * * *'
  workflow_dispatch:
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: setup-node
              uses: actions/setup-node@v3
            - name: build
              run: |
               npm install 
               npm run build
               npm run m3u
            - name: Deploy
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./m3u
                  cname: vodtv.cn/iptv
