name: update
on:  
  watch:
    types: [started]
  schedule:
    - cron: 0,30 * * * *
  workflow_dispatch:
jobs:
    build:
        runs-on: ubuntu-lates
        steps:
            - uses: actions/checkout@v3
            - name: Use Node.js
              uses: actions/setup-node@v3
              with:
                cache: 'npm'
            - run: npm i
            - run: npm run build
            - run: npm run Deploy
            
            - name: "Jekyll theme"
              run: mv ./_config.temp.yml ./m3u/_config.yml
              
            - name: Deploy
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./m3u
                  enable_jekyll: true
                  cname: m3u.vodtv.cn
