name: deploy
on:  
  workflow_dispatch:
env: 
  NODE_VERSION: '14.x'  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
          
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
            
    - name: npm install npm
      run: |     
        npm install
        npm run build --if-present
        npm run m3u --if-present
            
    - name: "Jekyll theme"
      run: mv ./_config.temp.yml ./m3u/_config.yml 
      
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./m3u
        enable_jekyll: true
        cname: m3u.vodtv.cn
