name: deploy
on:  
  workflow_dispatch:
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3   
      with:
        node-version: ${{ matrix.node-version }}
        cache: "npm"
    - name:  Install and Build
      run: |   
        npm install yarn -g &&  yarn install
        yarn build && yarn run m3u
            
    - name: "Jekyll theme"
      run: mv ./_config.temp.yml ./m3u/_config.yml
      
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GH_DOTCOM_TOKEN }}
        publish_dir: ./m3u
        enable_jekyll: true
        cname: m3u.vodtv.cn
   
