name: deploy
on:
  workflow_dispatch:
  push:
    branches:
      - main
  
jobs:
   Update:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3  
            - uses: actions/setup-node@v3
              if: ${{ !env.ACT }}
              with:
                  node-version: '18.18.2'
                  cache: 'npm'
            - name: install yarn
              run: npm install yarn -g
            - run: yarn install
            - run: yarn build
            - run: yarn run m3u
            
            - name: Deploy
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./m3u
                  cname: vodtv.cn/iptv
