name: Update Deploy

on:
  push:
    branches: [main]
  watch:
    types: [started]
  schedule:
    - cron:  "0 0,8 * * *"
  workflow_dispatch:
  
jobs:
   Update:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3  
            - name: Use Node.js 
              uses: actions/setup-node@v3
              with:
                  cache: "npm"
            - name: install yarn
              run: npm install yarn -g
            - run: yarn install
            - run: yarn build
            - run: yarn run m3u
            
            - name: Deploy
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./m3u
                  cname: vodtv.cn/iptv
